# Generated by Django 4.2.16 on 2024-10-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.TextField()),
                ('experience', models.CharField(choices=[('fresher', 'Fresher'), ('experienced', 'Experienced')], default='fresher', max_length=11)),
                ('batch_type', models.CharField(choices=[('weekday', 'Weekday'), ('weekend', 'Weekend')], default='weekday', max_length=10)),
                ('course', models.CharField(choices=[('select', 'Select'), ('python', 'Python'), ('java', 'Java'), ('data_science', 'Data Science')], default='select', max_length=20)),
                ('institute_reference', models.CharField(choices=[('select', 'Select'), ('online', 'Online Advertisement'), ('friend', 'Friend Referral'), ('social_media', 'Social Media'), ('other', 'Other')], default='select', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'courses_master',
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=500)),
                ('occupation', models.CharField(max_length=250)),
                ('experience', models.CharField(max_length=250)),
                ('batch_type', models.CharField(choices=[('all', 'All'), ('weekday', 'Weekday'), ('weekend', 'Weekend')], default='all', max_length=10)),
                ('branch_location', models.CharField(choices=[('virtual', 'Virtual'), ('btm', 'BTM'), ('marathahalli', 'Marathahalli'), ('kalyannagar', 'Kalyan Nagar')], default='virtual', max_length=100)),
                ('training_mode', models.CharField(choices=[('hybrid', 'Hybrid'), ('online', 'Online'), ('offline', 'Offline')], default='hybrid', max_length=100)),
                ('date_of_joining', models.DateField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('course', models.ManyToManyField(to='enquiries.option')),
            ],
            options={
                'db_table': 'trainer_details',
            },
        ),
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_joining', models.DateField()),
                ('student_name', models.CharField(max_length=100)),
                ('student_mobile', models.CharField(max_length=15)),
                ('student_email', models.CharField(max_length=250)),
                ('student_address', models.CharField(max_length=500)),
                ('student_pincode', models.CharField(max_length=10)),
                ('course_name', models.CharField(max_length=100)),
                ('total_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_remaining', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer')], max_length=20)),
                ('last_date_to_pay', models.DateField()),
                ('batch_type', models.CharField(choices=[('all', 'All'), ('Weekday', 'Weekday'), ('Weekend', 'Weekend')], max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('trainer_name', models.ManyToManyField(to='enquiries.trainer')),
            ],
            options={
                'db_table': 'student_details',
            },
        ),
    ]
