# Generated by Django 4.2.16 on 2024-09-11 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='batch_type',
            field=models.CharField(choices=[('weekday', 'Weekday'), ('weekend', 'Weekend')], default='weekday', max_length=10),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='course',
            field=models.CharField(choices=[('python', 'Python'), ('java', 'Java'), ('data_science', 'Data Science')], default='python', max_length=20),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='experience',
            field=models.CharField(choices=[('fresher', 'Fresher'), ('experienced', 'Experienced')], default='fresher', max_length=11),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='institute_reference',
            field=models.CharField(choices=[('online', 'Online Advertisement'), ('friend', 'Friend Referral'), ('social_media', 'Social Media'), ('other', 'Other')], default='online', max_length=20),
        ),
    ]
