# Generated by Django 4.2.16 on 2024-10-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentregistration',
            name='trainer_name',
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='trainer_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
