# Generated by Django 4.2.16 on 2024-09-11 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0002_enquiry_batch_type_enquiry_course_enquiry_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('date_of_joining', models.DateField()),
                ('student_name', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('total_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remaining_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer')], max_length=20)),
                ('trainer_name', models.CharField(max_length=100)),
                ('batch_type', models.CharField(choices=[('Weekday', 'Weekday'), ('Weekend', 'Weekend')], max_length=10)),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
    ]
