# Generated by Django 4.2.16 on 2024-10-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0003_remove_studentregistration_trainer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='fee_remaining',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='last_date_to_pay',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='student_pincode',
            field=models.IntegerField(max_length=10),
        ),
    ]
