# Generated by Django 5.1.1 on 2024-09-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0004_trainer_alter_enquiry_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='branch_location',
            field=models.CharField(choices=[('select', 'Select'), ('btm', 'BTM'), ('marathahalli', 'Marathahalli'), ('kalyannagar', 'Kalyan Nagar')], default='select', max_length=100),
        ),
        migrations.AddField(
            model_name='trainer',
            name='training_mode',
            field=models.CharField(choices=[('select', 'Select'), ('online', 'Online'), ('offline', 'Offline')], default='select', max_length=100),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='course',
            field=models.CharField(choices=[('select', 'Select'), ('python', 'Python'), ('java', 'Java'), ('data_science', 'Data Science'), ('dba', 'Database Administrator'), ('php', 'PHP')], default='select', max_length=250),
        ),
    ]
