# Generated by Django 4.2.16 on 2024-10-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0004_alter_studentregistration_fee_remaining_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='remarks',
            field=models.TextField(null=True),
        ),
    ]
