# Generated by Django 4.2.16 on 2024-10-12 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0005_alter_studentregistration_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentregistration',
            name='trainer_name',
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='trainer_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enquiries.trainer'),
        ),
    ]
