# Generated by Django 5.1.1 on 2024-09-19 14:58

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0005_trainer_branch_location_trainer_training_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='course',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('select', 'Select'), ('python', 'Python'), ('java', 'Java'), ('data_science', 'Data Science'), ('dba', 'Database Administrator'), ('php', 'PHP')], max_length=39),
        ),
    ]
