# Generated by Django 4.2.16 on 2024-10-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0008_paymentdetails_receipt_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetails',
            name='receipt_year',
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='receipt_no',
            field=models.CharField(max_length=20),
        ),
    ]
